/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.funcionarios_app.vistas;

import com.funcionarios_app.interfaces.FuncionarioOperaciones;
import com.funcionarios_app.modelos.Funcionario;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NATSU DRAGNEEL
 */
public class IUD_FuncionariosDB extends javax.swing.JFrame {

    String columnas[] = {"ID", "N° de Identificación", "Tipo Identificación",
        "Nombres", "Apellidos", "Estado civil", "Sexo", "Dirección", "Telefono",
        "Fecha nacimiento"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
    List<Object[]> listado = new ArrayList<>();
    FuncionarioOperaciones operacion = new FuncionarioOperaciones();

    public IUD_FuncionariosDB() {
        initComponents();
        this.cargarDatosTabla();

        for (String item : operacion.listarTiposIdentificaciones()) {
            cbxTipoIdentificacion.addItem(item);
        }
    }

    private void cargarDatosTabla() {
        this.listado = operacion.listarFuncionarios();
        modelo.setNumRows(0);

        for (Object[] funcionario : this.listado) {
            modelo.addRow(funcionario);
        }
        tblFuncionarios.setModel(modelo);
    }

    public void limpiarCamposDeTexto() {
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtEstadoCivil.setText("");
        txtFechaNacimiento.setText("");
        txtNombres.setText("");
        txtNumeroIdentificacion.setText("");
        cbxSexo.setSelectedItem("-- Seleccione --");
        txtTelefono.setText("");
        cbxTipoIdentificacion.setSelectedItem("-- Seleccione --");
    }

    public Boolean validarCampoVacio(String campo, String label) {
        if (campo.trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingresa el " + label);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelOpciones = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        faviconInicio = new javax.swing.JLabel();
        panelInicioBuscar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logoInicio = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        panelFuncionarios = new javax.swing.JPanel();
        faviconInicio1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnRecargar = new javax.swing.JButton();
        panelGestion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroIdentificacion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        cbxTipoIdentificacion = new javax.swing.JComboBox<>();
        cbxSexo = new javax.swing.JComboBox<>();
        panelInfo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblNumeroIdentificacion = new javax.swing.JLabel();
        lblTipoIdentificacion = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpciones.setBackground(new java.awt.Color(255, 255, 255));

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setForeground(new java.awt.Color(255, 255, 255));
        panelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faviconInicio.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        faviconInicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        faviconInicio.setText("Inicio");
        panelInicio.add(faviconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelInicioBuscar.setBackground(new java.awt.Color(136, 212, 234));

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));

        logoInicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(logoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel39.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Funcionarios DB");

        javax.swing.GroupLayout panelInicioBuscarLayout = new javax.swing.GroupLayout(panelInicioBuscar);
        panelInicioBuscar.setLayout(panelInicioBuscarLayout);
        panelInicioBuscarLayout.setHorizontalGroup(
            panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioBuscarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(706, Short.MAX_VALUE))
            .addGroup(panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInicioBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelInicioBuscarLayout.setVerticalGroup(
            panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInicioBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel39)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelInicio.add(panelInicioBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 990, -1));

        btnEliminar.setBackground(new java.awt.Color(13, 71, 161));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelInicio.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 90, 40));

        btnActualizar.setBackground(new java.awt.Color(13, 71, 161));
        btnActualizar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        panelInicio.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 100, 40));

        btnBuscar.setBackground(new java.awt.Color(13, 71, 161));
        btnBuscar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelInicio.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 90, 40));

        txtBusqueda.setFont(new java.awt.Font("Roboto Light", 1, 13)); // NOI18N
        txtBusqueda.setBorder(null);
        txtBusqueda.setCaretColor(new java.awt.Color(153, 153, 153));
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        panelInicio.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 290, 40));
        panelInicio.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 330, 10));

        panelOpciones.addTab("Inicio", panelInicio);

        panelFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        panelFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faviconInicio1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        faviconInicio1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        faviconInicio1.setText("Funcionarios");
        panelFuncionarios.add(faviconInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Funcionarios DB");
        panelFuncionarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N
        jLabel2.setText("jLabel2");
        panelFuncionarios.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 150, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\city.png")); // NOI18N
        jLabel1.setText("jLabel1");
        panelFuncionarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 290, 500));

        jPanel4.setBackground(new java.awt.Color(136, 212, 234));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFuncionarios.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 290, 110));

        tblFuncionarios.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "N° Identificación", "Tipo Identificación", "Nombres", "Apellidos", "Estado civil", "Sexo", "Dirección", "Telefono", "Fecha nacimiento"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        panelFuncionarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 680, 500));

        btnRecargar.setBackground(new java.awt.Color(255, 255, 255));
        btnRecargar.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\refresh.png")); // NOI18N
        btnRecargar.setBorder(null);
        btnRecargar.setBorderPainted(false);
        btnRecargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        panelFuncionarios.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 40, 40));

        panelOpciones.addTab("Funcionarios", panelFuncionarios);

        panelGestion.setBackground(new java.awt.Color(255, 255, 255));
        panelGestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        jLabel4.setText("Gestión Funcionarios");
        panelGestion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 60));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setText("Numero de Identificación");
        panelGestion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 30));

        txtNumeroIdentificacion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtNumeroIdentificacion.setBorder(null);
        txtNumeroIdentificacion.setCaretColor(new java.awt.Color(153, 153, 153));
        txtNumeroIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroIdentificacionActionPerformed(evt);
            }
        });
        panelGestion.add(txtNumeroIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, 30));
        panelGestion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, 10));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel7.setText("Tipo de Identificación");
        panelGestion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel8.setText("Nombres");
        panelGestion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(153, 153, 153));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        panelGestion.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 300, 30));
        panelGestion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 300, 10));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel9.setText("Apellidos");
        panelGestion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 30));

        txtApellidos.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtApellidos.setBorder(null);
        txtApellidos.setCaretColor(new java.awt.Color(153, 153, 153));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        panelGestion.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, 30));
        panelGestion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 300, 10));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel10.setText("Estado Civil");
        panelGestion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 30));

        txtEstadoCivil.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtEstadoCivil.setBorder(null);
        txtEstadoCivil.setCaretColor(new java.awt.Color(153, 153, 153));
        txtEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCivilActionPerformed(evt);
            }
        });
        panelGestion.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 300, 30));
        panelGestion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 300, 10));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel12.setText("Dirección");
        panelGestion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, 30));

        txtDireccion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.setCaretColor(new java.awt.Color(153, 153, 153));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        panelGestion.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 300, 30));
        panelGestion.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 290, 10));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel13.setText("Teléfono");
        panelGestion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, 30));

        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.setCaretColor(new java.awt.Color(153, 153, 153));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        panelGestion.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 300, 30));
        panelGestion.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 290, 10));

        txtFechaNacimiento.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtFechaNacimiento.setBorder(null);
        txtFechaNacimiento.setCaretColor(new java.awt.Color(153, 153, 153));
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });
        panelGestion.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 300, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento");
        panelGestion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 190, 30));
        panelGestion.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 290, 10));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel11.setText("Sexo");
        panelGestion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 130, 30));

        jPanel5.setBackground(new java.awt.Color(136, 212, 234));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGestion.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -10, 290, 120));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Funcionarios DB");
        panelGestion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 250, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N
        jLabel14.setText("jLabel2");
        panelGestion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 150, 140));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\city.png")); // NOI18N
        jLabel15.setText("jLabel1");
        panelGestion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 290, 510));

        btnAgregar.setBackground(new java.awt.Color(13, 71, 161));
        btnAgregar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelGestion.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 100, 40));

        cbxTipoIdentificacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxTipoIdentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --" }));
        cbxTipoIdentificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cbxTipoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoIdentificacionActionPerformed(evt);
            }
        });
        panelGestion.add(cbxTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 300, 30));

        cbxSexo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "M", "F", "O" }));
        cbxSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cbxSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoActionPerformed(evt);
            }
        });
        panelGestion.add(cbxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 290, 30));

        panelOpciones.addTab("Gestión funcionarios", panelGestion);

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        jLabel17.setText("Información");
        panelInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 60));

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel18.setText("Numero de Identificación");
        panelInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, 30));

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel19.setText("Tipo de Identificación");
        panelInfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 30));

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel20.setText("Nombres");
        panelInfo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 130, 30));

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel21.setText("Apellidos");
        panelInfo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 130, 30));

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel22.setText("Estado Civil");
        panelInfo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 130, 30));

        jLabel23.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel23.setText("Dirección");
        panelInfo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 130, 30));

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel24.setText("Teléfono");
        panelInfo.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 130, 30));

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel25.setText("Fecha de Nacimiento");
        panelInfo.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 130, 30));

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel26.setText("Sexo");
        panelInfo.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 30));

        lblSexo.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblSexo.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 160, 30));

        lblNumeroIdentificacion.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblNumeroIdentificacion.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblNumeroIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 160, 30));

        lblTipoIdentificacion.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblTipoIdentificacion.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 160, 30));

        lblNombres.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblNombres.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 170, 30));

        lblEstadoCivil.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblEstadoCivil.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 170, 30));

        lblDireccion.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblDireccion.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 180, 30));

        lblTelefono.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblTelefono.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 170, 30));

        lblFechaNacimiento.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblFechaNacimiento.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 160, 30));

        jPanel6.setBackground(new java.awt.Color(136, 212, 234));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelInfo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 290, 110));

        jLabel37.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Funcionarios DB");
        panelInfo.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 250, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N
        jLabel35.setText("jLabel2");
        panelInfo.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 150, 140));

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\city.png")); // NOI18N
        jLabel36.setText("jLabel1");
        panelInfo.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 290, 500));

        lblApellidos.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblApellidos.setText("xxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 160, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\avatar.png")); // NOI18N
        jLabel27.setText("jLabel27");
        panelInfo.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 100, 90));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\card.PNG")); // NOI18N
        jLabel28.setText("jLabel28");
        panelInfo.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 440, 520));

        panelOpciones.addTab("Información", panelInfo);

        panelPrincipal.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (txtBusqueda.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingresa el numero de identificación");
        } else {
            Funcionario funcionarioEncontrado = operacion.buscarFuncionario(txtBusqueda.getText());

            if (funcionarioEncontrado.getNumeroIdentificacion() == null) {
                JOptionPane.showMessageDialog(null, "El funcionario con numero de "
                        + "identificacion '" + txtBusqueda.getText() + "' no existe");
            } else {
                panelOpciones.setSelectedIndex(3);
                lblNumeroIdentificacion.setText(funcionarioEncontrado.getNumeroIdentificacion());
                lblTipoIdentificacion.setText(funcionarioEncontrado.getTipoIdentificacion());
                lblNombres.setText(funcionarioEncontrado.getNombres());
                lblApellidos.setText(funcionarioEncontrado.getApellidos());
                lblEstadoCivil.setText(funcionarioEncontrado.getEstadoCivil());
                lblDireccion.setText(funcionarioEncontrado.getDireccion());
                lblSexo.setText(String.valueOf(funcionarioEncontrado.getSexo()));
                lblTelefono.setText(funcionarioEncontrado.getTelefono());
                lblFechaNacimiento.setText(funcionarioEncontrado.getFechaNacimiento().toString());
                txtBusqueda.setText("");

            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO: Eliminar Campo
        if (txtBusqueda.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingresa el numero de identificación");
        } else {
            Funcionario funcionario = operacion.buscarFuncionario(txtBusqueda.getText());
            
            if(funcionario.getNumeroIdentificacion() == null) {
                JOptionPane.showMessageDialog(null, "El funcionario con numero de "
                        + "identificacion '" + txtBusqueda.getText() + "' no existe");
                return;
            } else {
                int opt = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar este funcionario?", "Confirmar salida",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if (opt == 0) {
                     operacion.eliminarFuncionario(funcionario);
                     txtBusqueda.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCivilActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtNumeroIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroIdentificacionActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO: Agregar un nuevo funcionario
        Funcionario nuevoFuncionario = new Funcionario();

        if (btnAgregar.getText().equals("Agregar")) {
            String campo = txtNumeroIdentificacion.getText();
            if (this.validarCampoVacio(campo, "numero de identificación")) {
                nuevoFuncionario.setNumeroIdentificacion(campo);
            } else {
                return;
            }

            campo = cbxTipoIdentificacion.getSelectedItem().toString();
            if (cbxTipoIdentificacion.getSelectedItem() == "-- Seleccione --") {
                JOptionPane.showMessageDialog(null, "Ingresa el tipo de identificación");
                return;
            } else {
                nuevoFuncionario.setTipoIdentificacion(campo);
            }

            campo = txtNombres.getText();
            if (this.validarCampoVacio(campo, "nombres")) {
                nuevoFuncionario.setNombres(campo);
            } else {
                return;
            }

            campo = txtApellidos.getText();
            if (this.validarCampoVacio(campo, "apellidos")) {
                nuevoFuncionario.setApellidos(campo);
            } else {
                return;
            }

            campo = txtEstadoCivil.getText();
            if (this.validarCampoVacio(campo, "estado civil")) {
                nuevoFuncionario.setEstadoCivil(campo);
            } else {
                return;
            }

            campo = txtDireccion.getText();
            if (this.validarCampoVacio(campo, "dirección")) {
                nuevoFuncionario.setDireccion(campo);
            } else {
                return;
            }

            campo = txtTelefono.getText();
            if (this.validarCampoVacio(campo, "telefono")) {
                nuevoFuncionario.setTelefono(txtTelefono.getText());
            } else {
                return;
            }

            campo = txtFechaNacimiento.getText();
            try {
                if (this.validarCampoVacio(campo, "fecha de nacimiento")) {
                    nuevoFuncionario.setFechaNacimiento(Date.valueOf(campo));
                } else {
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Formato de fecha invalido. Utiliza 'YYYY-MM-DD'");
                return;
            }

            char campoChar = cbxSexo.getSelectedItem().toString().charAt(0);
            if (cbxSexo.getSelectedItem() == "-- Seleccione --") {
                JOptionPane.showMessageDialog(null, "Ingresa el sexo");
                return;
            } else {
                nuevoFuncionario.setSexo(campoChar);
            }

            operacion.crearFuncionario(nuevoFuncionario);
            this.limpiarCamposDeTexto();
        } else {
            String campo = txtNumeroIdentificacion.getText();
            nuevoFuncionario.setNumeroIdentificacion(campo);

            campo = cbxTipoIdentificacion.getSelectedItem().toString();
            if (cbxTipoIdentificacion.getSelectedItem() == "-- Seleccione --") {
                JOptionPane.showMessageDialog(null, "Ingresa el tipo de identificación");
                return;
            } else {
                nuevoFuncionario.setTipoIdentificacion(campo);
            }

            campo = txtNombres.getText();
            if (this.validarCampoVacio(campo, "nombres")) {
                nuevoFuncionario.setNombres(campo);
            } else {
                return;
            }

            campo = txtApellidos.getText();
            if (this.validarCampoVacio(campo, "apellidos")) {
                nuevoFuncionario.setApellidos(campo);
            } else {
                return;
            }

            campo = txtEstadoCivil.getText();
            if (this.validarCampoVacio(campo, "estado civil")) {
                nuevoFuncionario.setEstadoCivil(campo);
            } else {
                return;
            }

            campo = txtDireccion.getText();
            if (this.validarCampoVacio(campo, "dirección")) {
                nuevoFuncionario.setDireccion(campo);
            } else {
                return;
            }

            campo = txtTelefono.getText();
            if (this.validarCampoVacio(campo, "telefono")) {
                nuevoFuncionario.setTelefono(txtTelefono.getText());
            } else {
                return;
            }

            campo = txtFechaNacimiento.getText();
            if (this.validarCampoVacio(campo, "fecha de nacimiento")) {
                nuevoFuncionario.setFechaNacimiento(Date.valueOf(campo));
            } else {
                return;
            }

            char campoChar = cbxSexo.getSelectedItem().toString().charAt(0);
            if (cbxSexo.getSelectedItem() == "-- Seleccione --") {
                JOptionPane.showMessageDialog(null, "Ingresa el sexo");
                return;
            } else {
                nuevoFuncionario.setSexo(campoChar);
            }

            operacion.actualizarFuncionario(nuevoFuncionario);
            this.limpiarCamposDeTexto();
            btnAgregar.setText("Agregar");
            txtNumeroIdentificacion.setEditable(true);
            txtFechaNacimiento.setEditable(true);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        this.cargarDatosTabla();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO: Actualizar funcionario
        if (txtBusqueda.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingresa el numero de identificación");
        } else {
            Funcionario funcionarioEncontrado = operacion.buscarFuncionario(txtBusqueda.getText());

            if (funcionarioEncontrado.getNumeroIdentificacion() == null) {
                JOptionPane.showMessageDialog(null, "El funcionario con numero de "
                        + "identificacion '" + txtBusqueda.getText() + "' no existe");
            } else {
                btnAgregar.setText("Editar");
                panelOpciones.setSelectedIndex(2);

                txtNumeroIdentificacion.setEditable(false);
                txtNumeroIdentificacion.setText(funcionarioEncontrado.getNumeroIdentificacion());

                cbxTipoIdentificacion.setSelectedItem(funcionarioEncontrado.getTipoIdentificacion());
                txtNombres.setText(funcionarioEncontrado.getNombres());
                txtApellidos.setText(funcionarioEncontrado.getApellidos());
                txtEstadoCivil.setText(funcionarioEncontrado.getEstadoCivil());
                txtDireccion.setText(funcionarioEncontrado.getDireccion());
                cbxSexo.setSelectedItem(String.valueOf(funcionarioEncontrado.getSexo()));
                txtTelefono.setText(funcionarioEncontrado.getTelefono());

                txtFechaNacimiento.setText(funcionarioEncontrado.getFechaNacimiento().toString());
                txtFechaNacimiento.setEditable(false);
                txtBusqueda.setText("");
            }
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbxTipoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoIdentificacionActionPerformed

    private void cbxSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUD_FuncionariosDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxTipoIdentificacion;
    private javax.swing.JLabel faviconInicio;
    private javax.swing.JLabel faviconInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumeroIdentificacion;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoIdentificacion;
    private javax.swing.JLabel logoInicio;
    private javax.swing.JPanel panelFuncionarios;
    private javax.swing.JPanel panelGestion;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelInicioBuscar;
    private javax.swing.JTabbedPane panelOpciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroIdentificacion;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
