/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.funcionarios_app.vistas;

import com.funcionarios_app.interfaces.FuncionarioOperaciones;
import com.funcionarios_app.modelos.Funcionario;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NATSU DRAGNEEL
 */
public class IUD_FuncionariosDB extends javax.swing.JFrame {
    String columnas[] = {"ID", "N° de Identificación", "Tipo Identificación", 
        "Nombres", "Apellidos", "Estado civil", "Sexo", "Dirección", "Telefono", 
        "Fecha nacimiento"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
    List<Object[]> listado = new ArrayList<>();
    FuncionarioOperaciones operacion = new FuncionarioOperaciones();

    public IUD_FuncionariosDB() {
        initComponents();
        this.cargarDatosTabla();
    }
    
    private void cargarDatosTabla() {
        this.listado = operacion.listarFuncionarios();
        modelo.setNumRows(0);
        
        for(Object [] funcionario : this.listado) {
            modelo.addRow(funcionario);
        }
        tblFuncionarios.setModel(modelo);
    }
    
    public void limpiarCamposDeTexto() {
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtEstadoCivil.setText("");
        txtFechaNacimiento.setText("");
        txtNombres.setText("");
        txtNumeroIdentificacion.setText("");
        txtSexo.setText("");
        txtTelefono.setText("");
        txtTipoIdentificacion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelOpciones = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        faviconInicio = new javax.swing.JLabel();
        panelInicioBuscar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logoInicio = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        panelFuncionarios = new javax.swing.JPanel();
        faviconInicio1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnRecargar = new javax.swing.JButton();
        panelGestion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroIdentificacion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtTipoIdentificacion = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txtSexo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpciones.setBackground(new java.awt.Color(255, 255, 255));

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setForeground(new java.awt.Color(255, 255, 255));
        panelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faviconInicio.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        faviconInicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        faviconInicio.setText("Inicio");
        panelInicio.add(faviconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelInicioBuscar.setBackground(new java.awt.Color(136, 212, 234));

        jPanel1.setBackground(new java.awt.Color(13, 71, 161));

        logoInicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(logoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel39.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Funcionarios DB");

        javax.swing.GroupLayout panelInicioBuscarLayout = new javax.swing.GroupLayout(panelInicioBuscar);
        panelInicioBuscar.setLayout(panelInicioBuscarLayout);
        panelInicioBuscarLayout.setHorizontalGroup(
            panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioBuscarLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(706, Short.MAX_VALUE))
            .addGroup(panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInicioBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelInicioBuscarLayout.setVerticalGroup(
            panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelInicioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelInicioBuscarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel39)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelInicio.add(panelInicioBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 990, -1));

        btnEliminar.setBackground(new java.awt.Color(13, 71, 161));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelInicio.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 90, 40));

        btnActualizar.setBackground(new java.awt.Color(13, 71, 161));
        btnActualizar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInicio.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 100, 40));

        btnBuscar.setBackground(new java.awt.Color(13, 71, 161));
        btnBuscar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelInicio.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 90, 40));

        jTextField11.setFont(new java.awt.Font("Roboto Light", 1, 13)); // NOI18N
        jTextField11.setBorder(null);
        jTextField11.setCaretColor(new java.awt.Color(153, 153, 153));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        panelInicio.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 290, 40));
        panelInicio.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 330, 10));

        panelOpciones.addTab("Inicio", panelInicio);

        panelFuncionarios.setBackground(new java.awt.Color(255, 255, 255));
        panelFuncionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faviconInicio1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        faviconInicio1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        faviconInicio1.setText("Funcionarios");
        panelFuncionarios.add(faviconInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Funcionarios DB");
        panelFuncionarios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 250, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N
        jLabel2.setText("jLabel2");
        panelFuncionarios.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 150, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\city.png")); // NOI18N
        jLabel1.setText("jLabel1");
        panelFuncionarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 290, 500));

        jPanel4.setBackground(new java.awt.Color(136, 212, 234));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFuncionarios.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 290, 110));

        tblFuncionarios.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "N° Identificación", "Tipo Identificación", "Nombres", "Apellidos", "Estado civil", "Sexo", "Dirección", "Telefono", "Fecha nacimiento"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        panelFuncionarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 650, 470));

        btnRecargar.setBackground(new java.awt.Color(255, 255, 255));
        btnRecargar.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\refresh.png")); // NOI18N
        btnRecargar.setBorder(null);
        btnRecargar.setBorderPainted(false);
        btnRecargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        panelFuncionarios.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 40, 40));

        panelOpciones.addTab("Funcionarios", panelFuncionarios);

        panelGestion.setBackground(new java.awt.Color(255, 255, 255));
        panelGestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        jLabel4.setText("Gestión Funcionarios");
        panelGestion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 60));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setText("Numero de Identificación");
        panelGestion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 30));

        txtNumeroIdentificacion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtNumeroIdentificacion.setBorder(null);
        txtNumeroIdentificacion.setCaretColor(new java.awt.Color(153, 153, 153));
        txtNumeroIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroIdentificacionActionPerformed(evt);
            }
        });
        panelGestion.add(txtNumeroIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, 30));
        panelGestion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, 10));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel7.setText("Tipo de Identificación");
        panelGestion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 30));

        txtTipoIdentificacion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtTipoIdentificacion.setBorder(null);
        txtTipoIdentificacion.setCaretColor(new java.awt.Color(153, 153, 153));
        txtTipoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoIdentificacionActionPerformed(evt);
            }
        });
        panelGestion.add(txtTipoIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, 30));
        panelGestion.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 300, 10));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel8.setText("Nombres");
        panelGestion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        txtNombres.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(153, 153, 153));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        panelGestion.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 300, 30));
        panelGestion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 300, 10));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel9.setText("Apellidos");
        panelGestion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 30));

        txtApellidos.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtApellidos.setBorder(null);
        txtApellidos.setCaretColor(new java.awt.Color(153, 153, 153));
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        panelGestion.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, 30));
        panelGestion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 300, 10));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel10.setText("Estado Civil");
        panelGestion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 30));

        txtEstadoCivil.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtEstadoCivil.setBorder(null);
        txtEstadoCivil.setCaretColor(new java.awt.Color(153, 153, 153));
        txtEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoCivilActionPerformed(evt);
            }
        });
        panelGestion.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 300, 30));
        panelGestion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 300, 10));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel12.setText("Dirección");
        panelGestion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, 30));

        txtDireccion.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.setCaretColor(new java.awt.Color(153, 153, 153));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        panelGestion.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 300, 30));
        panelGestion.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 300, 10));

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel13.setText("Teléfono");
        panelGestion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, 30));

        txtTelefono.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.setCaretColor(new java.awt.Color(153, 153, 153));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        panelGestion.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 300, 30));
        panelGestion.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 300, 10));

        txtFechaNacimiento.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtFechaNacimiento.setBorder(null);
        txtFechaNacimiento.setCaretColor(new java.awt.Color(153, 153, 153));
        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });
        panelGestion.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 300, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento");
        panelGestion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 190, 30));
        panelGestion.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 300, 10));

        txtSexo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtSexo.setBorder(null);
        txtSexo.setCaretColor(new java.awt.Color(153, 153, 153));
        txtSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexoActionPerformed(evt);
            }
        });
        panelGestion.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 300, 30));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel11.setText("Sexo");
        panelGestion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 130, 30));
        panelGestion.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 300, 10));

        jPanel5.setBackground(new java.awt.Color(136, 212, 234));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGestion.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -10, 290, 120));

        jLabel16.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Funcionarios DB");
        panelGestion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 250, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N
        jLabel14.setText("jLabel2");
        panelGestion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 150, 140));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\city.png")); // NOI18N
        jLabel15.setText("jLabel1");
        panelGestion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 290, 510));

        btnAgregar.setBackground(new java.awt.Color(13, 71, 161));
        btnAgregar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelGestion.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 100, 40));

        panelOpciones.addTab("Gestión funcionarios", panelGestion);

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\favicon.png")); // NOI18N
        jLabel17.setText("Información");
        panelInfo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 60));

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel18.setText("Numero de Identificación");
        panelInfo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 30));

        jLabel19.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel19.setText("Tipo de Identificación");
        panelInfo.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 30));

        jLabel20.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel20.setText("Nombres");
        panelInfo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel21.setText("Apellidos");
        panelInfo.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 30));

        jLabel22.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel22.setText("Estado Civil");
        panelInfo.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 30));

        jLabel23.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel23.setText("Dirección");
        panelInfo.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, 30));

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel24.setText("Teléfono");
        panelInfo.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, 30));

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel25.setText("Fecha de Nacimiento");
        panelInfo.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 190, 30));

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel26.setText("Sexo");
        panelInfo.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 130, 30));

        jLabel27.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 220, 30));

        jLabel28.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 30));

        jLabel29.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 220, 30));

        jLabel30.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 220, 30));

        jLabel31.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 220, 30));

        jLabel32.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 220, 30));

        jLabel33.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 220, 30));

        jLabel34.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 220, 30));

        jPanel6.setBackground(new java.awt.Color(136, 212, 234));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelInfo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 290, 110));

        jLabel37.setFont(new java.awt.Font("Roboto Black", 0, 32)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Funcionarios DB");
        panelInfo.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 250, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\logo.png")); // NOI18N
        jLabel35.setText("jLabel2");
        panelInfo.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 150, 140));

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\NATSU DRAGNEEL\\Documents\\NetBeansProjects\\funcionarios-app\\src\\main\\java\\com.funcionarios_app.assets\\city.png")); // NOI18N
        jLabel36.setText("jLabel1");
        panelInfo.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 290, 500));

        jLabel38.setText("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        panelInfo.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 220, 30));

        panelOpciones.addTab("Información", panelInfo);

        panelPrincipal.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoCivilActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtTipoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoIdentificacionActionPerformed

    private void txtNumeroIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroIdentificacionActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO: Agregar un nuevo funcionario
        Funcionario nuevoFuncionario = new Funcionario();
        
        nuevoFuncionario.setNumeroIdentificacion(txtNumeroIdentificacion.getText());
        nuevoFuncionario.setTipoIdentificacion(txtTipoIdentificacion.getText());
        nuevoFuncionario.setNombres(txtNombres.getText());
        nuevoFuncionario.setApellidos(txtApellidos.getText());
        nuevoFuncionario.setEstadoCivil(txtEstadoCivil.getText());
        nuevoFuncionario.setSexo(txtSexo.getText().charAt(0));
        nuevoFuncionario.setDireccion(txtDireccion.getText());
        nuevoFuncionario.setTelefono(txtTelefono.getText());
        nuevoFuncionario.setFechaNacimiento(Date.valueOf(txtFechaNacimiento.getText()));
        
        operacion.crearFuncionario(nuevoFuncionario);
        this.limpiarCamposDeTexto();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        // TODO add your handling code here:
        this.cargarDatosTabla();
    }//GEN-LAST:event_btnRecargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUD_FuncionariosDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUD_FuncionariosDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel faviconInicio;
    private javax.swing.JLabel faviconInicio1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JLabel logoInicio;
    private javax.swing.JPanel panelFuncionarios;
    private javax.swing.JPanel panelGestion;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelInicioBuscar;
    private javax.swing.JTabbedPane panelOpciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroIdentificacion;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoIdentificacion;
    // End of variables declaration//GEN-END:variables
}
